### ISSUE TITLE
Показано %s - %s з %s

### ISSUE THREAD

**Issue by maxim-pishnyak** [Joomla-Ukraine/uk-UA#15]
https://github.com/Joomla-Ukraine/uk-UA/blob/f61ebfc9151622efe50e12a839cb3c52ed894a26/uk-UA_3.x/language/uk-UA/uk-UA.lib_joomla.ini#L453
Показано %s - %s з %s

**Comment by DenysNosov** [comment]
На сайті що показує?

**Comment by Kostelano** [comment]
"Показано" вполне уместно, как по мне.
Дословный перевод, а в **en-GB** именно `Results %s - %s of %s`, не всегда правильно.

**Comment by DenysNosov** [comment]
Оновлено!
