### ISSUE TITLE
COM_USERS_EMAIL_PASSWORD_RESET_BODY

### ISSUE THREAD

**Issue by dmitrkov** [Joomla-Ukraine/uk-UA#16]
Некоректний переклад константи COM_USERS_EMAIL_PASSWORD_RESET_BODY у файлі \language\uk-UA\uk-UA.com_users.ini 
Англійскою мовою переклад виглядає 
COM_USERS_EMAIL_PASSWORD_RESET_BODY="Hello,\n\nA request has been made to reset your %s account password. To reset your password, you will need to submit this verification code to verify that the request was legitimate.\n\nThe verification code is %s\n\nSelect the URL below and proceed with resetting your password.\n\n %s \n\nThank you."
Українською мовою:
COM_USERS_EMAIL_PASSWORD_RESET_BODY="Вітаємо!\n\nВи або хтось інший зробили запит на зміну пароля до вашого облікового запису %s.\n\nЯкщо запит був створений вами, будь ласка, перейдіть по посиланню, наведеному нижче, щоб підтвердити код на зміну паролю та приступити до процедури зміни вашого паролю на новий.\n\n%s\n\nДякуємо!"

Як наслідок вихідний текст не містить посилання
"Вітаємо!

Ви або хтось інший зробили запит на зміну пароля до вашого облікового запису  Особистий кабінет споживача.

Якщо запит був створений вами, будь ласка, перейдіть по посиланню, наведеному нижче, щоб підтвердити код на зміну паролю та приступити до процедури зміни вашого паролю на новий.

9742a77499af880414a5985eaf98b9bd

Дякуємо!"

**Comment by dmitrkov** [comment]
Як приклад:
Вітаємо!\n\nВи або хтось інший зробили запит на зміну пароля до вашого облікового запису %s.\n\nЩоб скинути пароль, вам потрібно буде надіслати цей код підтвердження, щоб переконатися, що запит був законним.\n\nКод підтвердження %s\n\nПерейдіть по посиланню, наведеному нижче, щоб підтвердити код на зміну паролю та приступити до процедури зміни вашого паролю на новий.\n\n%s\n\nДякуємо!

**Comment by DenysNosov** [comment]
Чи могли б ви сформувати PR?
