### ISSUE TITLE
Missing files, Import and GHA are not running

### ISSUE THREAD

**Issue by tecpromotion** [Joomla-Ukraine/uk-UA#29]
Hi @denysdesign and @Kostelano 

Please check Commit 0d90e595928f68b547f36874c4ce7827d8b94730

Files were deleted that are important for the importer and for the core.

Please fix this as soon as possible, the GHA will not run cleanly as long as this is the case.
https://github.com/joomla/core-translations/actions/workflows/remote-get-ukrainian.yml

Thank you very much,
Stefan

**Comment by denysdesign** [comment]
Fix now!
It's OK?

Thank you!

**Comment by tecpromotion** [comment]
The installation/ folder is still missing.

**Comment by wojsmol** [comment]
@denysdesign Additionally please see that `@version` and `@date` headers are reverted in https://github.com/Joomla-Ukraine/uk-UA/commit/0d90e595928f68b547f36874c4ce7827d8b94730.

**Comment by denysdesign** [comment]
Fixed `@version`, `@date` and add `/installation` folder

Please check if everything is fine!

Thank you!

**Comment by tecpromotion** [comment]
GHA works now.
